// <auto-generated />
using System;
using DAL.Configuration.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations.SSMS
{
    [DbContext(typeof(HerdsyncDBContext))]
    [Migration("20250930194228_RFIDTags")]
    partial class RFIDTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Base.History.PregnanciesDetailHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OriginalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("prg_Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("prg_Pregnancy_End_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("prg_Pregnancy_Spot_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("spd_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HistoryId");

                    b.ToTable("PregnanciesHistory");
                });

            modelBuilder.Entity("DAL.Models.Base.History.SpeciesDetailHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OriginalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("prg_Pregnancy_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("spd_Age")
                        .HasColumnType("int");

                    b.Property<string>("spd_AgeGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("spd_Born_Or_Buy")
                        .HasColumnType("bit");

                    b.Property<bool>("spd_Branded")
                        .HasColumnType("bit");

                    b.Property<int?>("spd_Est_Years_Left")
                        .HasColumnType("int");

                    b.Property<string>("spd_Father")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spd_Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("spd_Last_Pregnancy")
                        .HasColumnType("datetime2");

                    b.Property<string>("spd_Medical_Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spd_Mother")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("spd_Number")
                        .HasColumnType("int");

                    b.Property<string>("spd_Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spd_Tag_Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("spd_Total_Offspring")
                        .HasColumnType("int");

                    b.Property<int?>("spd_Total_Pregnancies")
                        .HasColumnType("int");

                    b.Property<decimal>("spd_Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HistoryId");

                    b.ToTable("SpeciesHistory");
                });

            modelBuilder.Entity("DAL.Models.prg_Pregnancies_Detail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("prg_Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("prg_Pregnancy_End_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("prg_Pregnancy_Spot_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("spd_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("spd_Id");

                    b.ToTable("Pregnancies");
                });

            modelBuilder.Entity("DAL.Models.spd_Species_Detail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("prg_Pregnancy_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("spd_Age")
                        .HasColumnType("int");

                    b.Property<string>("spd_AgeGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("spd_Born_Or_Buy")
                        .HasColumnType("bit");

                    b.Property<bool>("spd_Branded")
                        .HasColumnType("bit");

                    b.Property<int?>("spd_Est_Years_Left")
                        .HasColumnType("int");

                    b.Property<string>("spd_Father")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("spd_Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("spd_Last_Pregnancy")
                        .HasColumnType("datetime2");

                    b.Property<string>("spd_Medical_Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("spd_Mother")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("spd_Number")
                        .HasColumnType("int");

                    b.Property<string>("spd_Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("spd_Tag_Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("spd_Total_Offspring")
                        .HasColumnType("int");

                    b.Property<int?>("spd_Total_Pregnancies")
                        .HasColumnType("int");

                    b.Property<decimal>("spd_Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("DAL.Models.stl_Species_Tag_Lookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("spd_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("stl_Tag_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("spd_Id");

                    b.ToTable("SpeciesTag");
                });

            modelBuilder.Entity("DAL.Models.prg_Pregnancies_Detail", b =>
                {
                    b.HasOne("DAL.Models.spd_Species_Detail", "Species")
                        .WithMany("Pregnancies")
                        .HasForeignKey("spd_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("DAL.Models.stl_Species_Tag_Lookup", b =>
                {
                    b.HasOne("DAL.Models.spd_Species_Detail", "Species")
                        .WithMany()
                        .HasForeignKey("spd_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("DAL.Models.spd_Species_Detail", b =>
                {
                    b.Navigation("Pregnancies");
                });
#pragma warning restore 612, 618
        }
    }
}
